#!/bin/sh

OUT="$(date -u "+%F").tar"

(
  cd "$HOME" || exit
  find . -mindepth 1 -maxdepth 1 -type d |
  grep -v "\./Videos"                    |
  grep -v "\./\."                        |
  tar -acvf "$OUT" -T -
)
