#!/bin/sh

if [ "$#" -ne 1 ]
then
  echo "Usage: restore-backup <file>"
  exit
fi

if ! [ -e "$1" ]
then
  echo "Error: $1 does not exist."
  exit
fi

if ! [ ".tar" = ".${1##*.}" ]
then
  echo "Error: $1 is not a tarball."
  exit
fi

(
  cd "$HOME" || exit
  tar -xvmf "$1"
)
