#!/bin/sh

if [ "$#" -ne 1 ] && [ "$#" -ne 2 ]
then
  echo "Usage: restore <file> [pattern]"
  exit
fi

if ! [ -e "$1" ]
then
  echo "Error: $1 does not exist."
  exit
fi

if ! [ ".tar" = ".${1##*.}" ]
then
  echo "Error: $1 is not a tarball."
  exit
fi

(
  cd "$HOME" || exit
  tar -xvf "$1" "$2"
)
